if(NOT TARGET ggml AND NOT TARGET ggml::ggml)
    if(SD_USE_SYSTEM_GGML)
        find_package(ggml REQUIRED)
    else()
        add_subdirectory("${SD_GGML_SOURCE_DIR}" "${CMAKE_CURRENT_BINARY_DIR}/ggml")
    endif()
endif()
if(NOT TARGET ggml)
    add_library(ggml ALIAS ggml::ggml)
endif()

get_target_property(sd_ggml_imported ggml IMPORTED)
if(sd_ggml_imported)
    set(sd_ggml_private_include "${SD_GGML_SOURCE_DIR}/src")
else()
    get_target_property(sd_ggml_private_include ggml SOURCE_DIR)
endif()
if(NOT EXISTS "${sd_ggml_private_include}/ggml-impl.h")
    message(FATAL_ERROR "Set SD_GGML_SOURCE_DIR to the source tree matching the selected ggml library (ggml-impl.h is required).")
endif()
target_include_directories(${SD_LIB} PRIVATE "${sd_ggml_private_include}")
set_property(TARGET ${SD_LIB} PROPERTY SD_GGML_PRIVATE_INCLUDE_DIR "${sd_ggml_private_include}")

# The fused DiT ops come from scripts/unsloth/ggml-patches/0004; an unpatched ggml keeps the unfused H3 graph.
set(sd_ggml_header "${sd_ggml_private_include}/../include/ggml.h")
if(EXISTS "${sd_ggml_header}")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${sd_ggml_header}")
    file(STRINGS "${sd_ggml_header}" sd_ggml_h3_fused_ops REGEX "ggml_rope_pe_permute\\(")
    file(STRINGS "${sd_ggml_header}" sd_ggml_h3_fused_qk_norm REGEX "ggml_rope_pe_permute_rms\\(")
endif()
if(sd_ggml_h3_fused_ops)
    target_compile_definitions(${SD_LIB} PUBLIC SD_GGML_H3_FUSED_OPS)
else()
    message(STATUS "ggml lacks the fused DiT ops patch: MiniMax-H3 uses the unfused graph")
endif()
# The fused q/k RMS norm comes from patch 0005.
if(sd_ggml_h3_fused_qk_norm)
    target_compile_definitions(${SD_LIB} PUBLIC SD_GGML_H3_FUSED_QK_NORM)
endif()

if(SD_USE_UPSTREAM_GGML)
    target_compile_definitions(${SD_LIB} PUBLIC SD_USE_UPSTREAM_GGML)
    message(WARNING "Using upstream GGML: INT8 tensorwise/convrot is disabled and FP8 weights are converted to F16 at load time. Some operators may be unsupported and performance may be lower than with patched GGML.")
endif()
